### PR TITLE
Fix/stripe empty lines

### LINKED ISSUE #9: Bug: empty lines at the end of report
This issue appears only in the web app.
Screenshot 2019-12-12 at 14 23 15
However, Tg automatically strips empty lines.
Screenshot 2019-12-12 at 14 23 37

### PR DESCRIPTION
**Pull request by EeOneDown**
Fix #9

### CODE REVIEW

File: main/js/popup.js [hunk 1]
```diff
@@ -150,14 +150,10 @@ document.addEventListener('DOMContentLoaded', function() {
...
-    data.map((task) => {
-      // parse for html
-      savedOutput += `${selectedFields.map(field => task[field]).join(' - ')}<br/><br/>`;
-      // parse for copy
-      savedCopyOutput += `${selectedFields.map(field => task[field]).join(' - ')}\n\n`;
-    });
+    let parsedTasks = data.map(task => `${selectedFields.map(field => task[field]).join(' - ')}`);
+    savedOutput =`Отчёт за ${now.getDate()}.${now.getMonth() + 1}:<br/><br/>` + parsedTasks.join('<br/><br/>');
+    savedCopyOutput = parsedTasks.join('\n\n');
+
```
Comment (a-sakhautdinov) [inline main/js/popup.js]: nice work!
